### ISSUE TITLE
Trying to compile on 2026.1.3 and it fails

### ISSUE THREAD

**Issue by aususer** [Omniflux/esphome-tzspserial#1]
Compiling .pioenvs/outside_shed_airconditioner/src/esphome/components/uart/uart_component.cpp.o
src/esphome/components/tzsp_serial/TZSPSerial.cpp: In member function 'virtual void esphome::tzspserial::TZSPSerial::setup()':
src/esphome/components/tzsp_serial/TZSPSerial.cpp:14:71: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'uart_port_t' [-fpermissive]
   14 |     int err = uart_set_rx_timeout(this->idf_uart->get_hw_serial_number(), this->symbol_timeout_);
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                       |
      |                                                                       uint8_t {aka unsigned char}
In file included from src/esphome/components/uart/uart_component_esp_idf.h:5,
                 from src/esphome/components/tzsp_serial/TZSPSerial.h:5,
                 from src/esphome/components/tzsp_serial/TZSPSerial.cpp:5:
/data/cache/platformio/packages/framework-espidf/components/esp_driver_uart/include/driver/uart.h:763:43: note:   initializing argument 1 of 'esp_err_t uart_set_rx_timeout(uart_port_t, uint8_t)'
  763 | esp_err_t uart_set_rx_timeout(uart_port_t uart_num, const uint8_t tout_thresh);
      |                               ~~~~~~~~~~~~^~~~~~~~
src/esphome/components/tzsp_serial/TZSPSerial.cpp: In member function 'void esphome::tzspserial::TZSPSerial::uart_event_task()':
src/esphome/components/tzsp_serial/TZSPSerial.cpp:59:121: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'uart_port_t' [-fpermissive]
   59 |                     uart_get_buffered_data_len(static_cast<uart::IDFUARTComponent*>(this->parent_)->get_hw_serial_number(), &bufferLen);
      |                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                                                                         |
      |                                                                                                                         uint8_t {aka unsigned char}
/data/cache/platformio/packages/framework-espidf/components/esp_driver_uart/include/driver/uart.h:605:50: note:   initializing argument 1 of 'esp_err_t uart_get_buffered_data_len(uart_port_t, size_t*)'
  605 | esp_err_t uart_get_buffered_data_len(uart_port_t uart_num, size_t* size);
      |                                      ~~~~~~~~~~~~^~~~~~~~
*** [.pioenvs/outside_shed_airconditioner/src/esphome/components/tzsp_serial/TZSPSerial.cpp.o] Error 1
========================= [FAILED] Took 134.90 seconds =========================

**Comment by Omniflux** [comment]
I've pushed fb3924b which I think accounts for all the changes in ESPHome since I've last used this, but I am not able to test at the moment.

**Comment by aususer** [comment]
You are a GEM!
works and builds perfectly with the latest (2026.2) build of ESP home!

Thankyou!


> INFO Build Info: config_hash=0x7cf8b02f build_time_str=2026-02-04 16:57:35 +1100
> INFO Successfully compiled program.
> INFO Connecting to 192.168.0.123 port 3232...
> INFO Connected to 192.168.0.123
> INFO Uploading /data/build/outside_shed_airconditioner/.pioenvs/outside_shed_airconditioner/firmware.bin (948848 bytes)
> Uploading: [============================================================] 100% Done...
> 
> INFO Upload took 4.80 seconds, waiting for result...
> INFO OTA successful
> INFO Successfully uploaded program.
> INFO Starting log output from 192.168.0.123 using esphome API
> INFO Successfully resolved outside_shed_airconditioner @ 192.168.0.123 in 0.000s
> INFO Successfully connected to outside_shed_airconditioner @ 192.168.0.123 in 4.223s
> INFO Successful handshake with outside_shed_airconditioner @ 192.168.0.123 in 0.135s
> [17:07:27.038][I][app:206]: ESPHome version 2026.1.3 compiled on 2026-02-04 16:57:35 +1100
> [17:07:27.043][I][app:213]: ESP32 Chip: ESP32-C3 r0.3, 1 core(s)
> [17:07:27.043][C][logger:316]: Logger:
> [17:07:27.043][C][logger:316]:   Max Level: DEBUG
> [17:07:27.043][C][logger:316]:   Initial Level: DEBUG
> [17:07:27.047][C][logger:322]:   Log Baud Rate: 115200
> [17:07:27.047][C][logger:322]:   Hardware UART: USB_SERIAL_JTAG
> [17:07:27.075][C][logger:332]:   Task Log Buffer Size: 768 bytes
> [17:07:27.076][C][uart.idf:238]: UART Bus 0:
> [17:07:27.078][C][uart.idf:152]:   TX Pin: GPIO21
> [17:07:27.083][C][uart.idf:152]:   RX Pin: GPIO20
> [17:07:27.083][C][uart.idf:243]:   RX Buffer Size: 256
> [17:07:27.083][C][uart.idf:243]:   RX Full Threshold: 1
> [17:07:27.083][C][uart.idf:243]:   RX Timeout: 2
> [17:07:27.087][C][uart.idf:249]:   Baud Rate: 104 baud
> [17:07:27.087][C][uart.idf:249]:   Data Bits: 8
> [17:07:27.087][C][uart.idf:249]:   Parity: NONE
> [17:07:27.087][C][uart.idf:249]:   Stop bits: 1
> [17:07:27.095][C][uptime.sensor:016]: Uptime Sensor 'Uptime'
> [17:07:27.095][C][uptime.sensor:016]:   State Class: 'total_increasing'
> [17:07:27.095][C][uptime.sensor:016]:   Unit of Measurement: 's'
> [17:07:27.095][C][uptime.sensor:016]:   Accuracy Decimals: 0
> [17:07:27.096][C][uptime.sensor:026]:   Device Class: 'duration'
> [17:07:27.097][C][uptime.sensor:030]:   Icon: 'mdi:timer-outline'
> [17:07:27.107][C][uptime.sensor:033]:   Type: Seconds
> [17:07:27.108][C][restart.button:014]: Restart Button 'Restart'
> [17:07:27.114][C][restart.button:017]:   Icon: 'mdi:restart'
> [17:07:27.122][C][safe_mode.button:014]: Safe Mode Button 'Restart (Safe Mode)'
> [17:07:27.122][C][safe_mode.button:017]:   Icon: 'mdi:restart-alert'
> [17:07:27.131][C][esphome::tzsp_serial:040]: TZSPSerial
> [17:07:27.136][C][esphome::tzsp_serial:041]:   Destination: 192.168.0.111:37008
> [17:07:27.137][C][esphome::tzsp_serial:042]:   Protocol: 255
> [17:07:27.140][C][esphome::tzsp_serial:043]:   Discard protocol: 0
> [17:07:27.145][C][esphome::tzsp_serial:044]:   Frame size: 8
> [17:07:27.145][C][esphome::tzsp_serial:045]:   Symbol timeout: 2
> [17:07:27.149][C][esphome::tzsp_serial:046]:   Inverted: YES
> [17:07:27.176][C][captive_portal:128]: Captive Portal:
> [17:07:27.176][C][wifi:1304]: WiFi:
> [17:07:27.176][C][wifi:1304]:   Local MAC: 7C:DF:A1:B3:EC:AC
> [17:07:27.176][C][wifi:1304]:   Connected: YES
> [17:07:27.178][C][wifi:1037]:   IP Address: 192.168.0.123
> [17:07:27.192][C][wifi:1048]:   SSID: [redacted]
> [17:07:27.192][C][wifi:1048]:   BSSID: [redacted]
> [17:07:27.192][C][wifi:1048]:   Hostname: 'outside_shed_airconditioner'
> [17:07:27.192][C][wifi:1048]:   Signal strength: -47 dB ▂▄▆█
> [17:07:27.192][C][wifi:1048]:   Channel: 1
> [17:07:27.192][C][wifi:1048]:   Subnet: 255.255.255.0
> [17:07:27.192][C][wifi:1048]:   Gateway: 192.168.0.1
> [17:07:27.192][C][wifi:1048]:   DNS1: 192.168.0.1
> [17:07:27.192][C][wifi:1048]:   DNS2: 8.8.8.8
> [17:07:27.193][C][esphome.ota:075]: Over-The-Air updates:
> [17:07:27.193][C][esphome.ota:075]:   Address: outside_shed_airconditioner.local:3232
> [17:07:27.193][C][esphome.ota:075]:   Version: 2
> [17:07:27.195][C][esphome.ota:082]:   Password configured
> [17:07:27.208][C][safe_mode:021]: Safe Mode:
> [17:07:27.208][C][safe_mode:021]:   Successful after: 60s
> [17:07:27.208][C][safe_mode:021]:   Invoke after: 10 attempts
> [17:07:27.208][C][safe_mode:021]:   Duration: 300s
> [17:07:27.209][C][safe_mode:038]:   Bootloader rollback: supported
> [17:07:27.214][C][web_server.ota:231]: Web Server OTA
> [17:07:27.229][C][api:221]: Server:
> [17:07:27.229][C][api:221]:   Address: outside_shed_airconditioner.local:6053
> [17:07:27.229][C][api:221]:   Listen backlog: 4
> [17:07:27.229][C][api:221]:   Max connections: 8
> [17:07:27.230][C][api:228]:   Noise encryption: YES
> [17:07:27.238][C][mdns:177]: mDNS:
> [17:07:27.238][C][mdns:177]:   Hostname: outside_shed_airconditioner
> [17:07:28.971][D][esphome::tzsp_serial:074][UART_Event]: Discarded 4 bytes
> [17:07:31.016][D][esphome::tzsp_serial:074][UART_Event]: Discarded 4 bytes`

```

<img width="581" height="282" alt="Image" src="https://github.com/user-attachments/assets/6ed9a816-c8e3-48db-aa67-b081a6cb14b2" />

```
